#! for run this file you want the "REST Client" extension 
GET http://localhost:9990/api/v1/
# this route for get all user todo's

###
GET http://localhost:9990/api/v1/1
# this route for get one todo

###
POST http://localhost:9990/api/v1
# this route for create new todo
Content-Type: application/json

# this is a request body for test create new todo
{
    "title" : "homework",
    "description" : "javascript homework", 
    "constructiveUsers" : {
        "name" : "Dayan",
        "userId" : "u45s11",
        "userRole" : "mentor"
    }, 
    "assignedToUsers" :  {
        "name" : "Diana",
        "userId" : "u45s55",
        "userRole" : "student"
    }, 
    "createDate" : "2023-1-1", 
    "doneDate" : "2023-1-5"
}


###
DELETE http://localhost:9990/api/v1/1
# this route for delete one todo


###
PATCH http://localhost:9990/api/v1/1
# this route for update one todo
